<div id="header">
    <div id="header_content">
        <div id="header_menu_top">
            <div id="header_menu_top_left">
                <ul>
                    <li>Пятница <span>19.11.2010</span></li>
                    <li>Температура воздуха <span>+ 12 С</span></li>
                    <li> &#36; <span>31.18</span>&nbsp;&nbsp; &euro;  <span>38.26</span></li>
                </ul>
            </div>		
            <div id="header_menu_top_right">
                <ul>
                    <li><a href="#"><img src="/design/i/header_menu_top_img_1.png" alt="#" /></a></li>
                    <li><a href="#"><img src="/design/i/header_menu_top_img_2.png" alt="#"  /></a></li>
                    <li><a href="#"><img src="/design/i/header_menu_top_img_3.png" alt="#" /></a></li>
                    <li><a href="#"><span>Регистрация</span> / <span>Авторизация</span></a></li>
                </ul>
            </div>	
        </div>
        <div id="header_center">
            <div id="header_logo">
                <a href="index.html"><img src="/design/i/header_logo_left.png" alt="#" /></a>
            </div>
            <div class="header_search">
                <div class="button_search_header">
                    <form action="">
                        <fieldset>
                            <button type="submit">Пошук</button>
                        </fieldset>
                    </form>
                </div>
                <div class="text_search_header">
                    <form action="">
                        <fieldset>
                            <input id="name_1" name="name" type="text"  />
                        </fieldset>
                    </form>
                </div>
                <div class="clear_both">&nbsp;</div>
                <a href="#">Расширеный поиск</a>
            </div>
            <div class="clear_both">&nbsp;</div>
        </div>	
        <div id="header_menu_bottom">
            <div id="header_menu_bottom_1">
                <ul>
                    <li><a href="index.html">Главная</a></li>
                    <li class="active"><a href="/company">Компании</a></li>
                    <li><a href="news.html">Новости</a></li>
                    <li><a href="advertisment.html">Обьявления</a></li>
                    <li><a href="map.html">Карта</a></li>
                    <li><a href="/comunity">Общение</a></li>
                    <li><a href="investment.html">Инвестиции</a></li>
                    <li><a href="partnership.html">Партнерство</a></li>
                    <li><a href="ideas.html">Идеи</a></li>
                    <li><a href="analitics.html">Аналитика</a></li>
                    <li><a href="help.html">Справочная</a></li>
                    <li><a href="more.html">Еще</a></li>
                </ul>
            </div>
            <div id="header_menu_bottom_2">
                <ul>
                    <li><a href="#">Фабрики</a></li>
                    <li><a href="#">Заводы</a></li>
                    <li><a href="#">Фирмы</a></li>
                    <li class="active"><a href="#">Кондитерские</a></li>
                    <li><a href="#">Кафе</a></li>
                    <li><a href="#">Бары</a></li>
                    <li><a href="#">Рестораны</a></li>
                    <li><a href="#">Банки</a></li>
                    <li><a href="#">Досуг</a></li>
                </ul>
            </div>
        </div>
    </div><!--HEADER_CONTENT-->
</div><!--HEADER-->