<?php
$this->headLink()->appendStylesheet('/design/cms/css/style.css')
        ->appendStylesheet('/design/cms/jqueryui/jquery-ui-1.8.16.custom.css')
        ->appendStylesheet('/design/cms/jqueryui/jquery.ui.selectmenu.css')
        ->appendStylesheet('/design/cms/css/uniform.css')
        ->appendStylesheet('/design/cms/css/jquery.jcrop.css')
        ->appendStylesheet('/design/fancybox/jquery.fancybox-1.3.4.css')
        ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'), 'PREPEND');

$this->headScript()->appendFile('/design/cms/js/jquery-1.6.2.min.js')
        ->appendFile('/design/cms/js/jquery-ui-1.8.16.custom.min.js')
        ->appendFile('/design/cms/js/jquery.ui.dialog.js')
        ->appendFile('/design/cms/js/jquery.ui.nestedSortable.js')
        ->appendFile('/design/cms/js/jquery.ui.selectmenu.js')
        ->appendFile('/design/cms/js/jquery.uniform.min.js')
        ->appendFile('/design/cms/js/jquery.iframe-post-form.js')
        ->appendFile('/design/cms/js/jquery.jcrop.min.js')
        ->appendFile('/design/cms/js/jquery.json.js')
        ->appendFile('/design/cms/js/jquery.rastor.table.js')
        ->appendFile('/design/cms/js/jquery.rastor.messager.js')
        ->appendFile('/design/cms/js/jquery.rastor.pictures.js')
        ->appendFile('/design/cms/js/jquery.rastor.tree.js')
        ->appendFile('/design/fancybox/jquery.fancybox-1.3.4.pack.js')
        ->appendFile('/ckeditor/ckeditor.js')
        ->appendFile('/ckeditor/adapters/jquery.js');

echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->headStyle();
echo $this->headScript();
?>

<script type="text/javascript">
    jQuery.fn.exists = function() {
        return $(this).length;
    }
            
    $(document).ready(function(){
        $("form input[type=text], input[type=password], from textarea, from select, form input[type=file]").uniform();
        $('.msg').click(function(){
            $(this).fadeTo(350, 0);
            $(this).slideUp(350);
        });
                        
        $('.msg.autoFadeDown').click(function() {
            $(this).fadeTo(350, 0);
            $(this).slideUp(350);   
        }).delay(3000).fadeTo(350, 0).slideUp(350);
			
        $('button, input[type=button], input[type=submit], input[type=reset]').button();
        $('.wyswisg').ckeditor({
            'filebrowserBrowseUrl': '/ckeditor/kcfinder/browse.php?type=files',
            'filebrowserImageBrowseUrl': '/ckeditor/kcfinder/browse.php?type=images',
            'filebrowserFlashBrowseUrl': '/ckeditor/kcfinder/browse.php?type=flash',
            'filebrowserUploadUrl': '/ckeditor/kcfinder/upload.php?type=files',
            'filebrowserImageUploadUrl': '/ckeditor/kcfinder/upload.php?type=images',
            'filebrowserFlashUploadUrl': '/ckeditor/kcfinder/upload.php?type=flash'
        });
		
        $('.fancy').fancybox();
    });
</script>
