<div id="footer">
    <div id="footer_1">
        <ul>
            <li><a href="#">О проекте</a></li>
            <li><a href="#">Реклама на сайте</a></li>
            <li><a href="#">Карта сайта</a></li>
            <li><a href="#">Реклама</a></li>
            <li><a href="#">Статистика</a></li>
        </ul>
    </div>
    <div id="footer_2">
        <div id="footer_2_link">
            <a href="#">© 2010 Informbiz.com.ua</a>
            <p>All rights reserved</p>
        </div>
        <a href="#"><img src="/design/i/banner_bottom.png" alt="#"></a>
        <img src="/design/i/gray_block.png" alt="#" style="width:88px; height: 31px; float: right; padding: 30px 0 0 0;">
        <img src="/design/i/gray_block.png" alt="#" style="width:88px; height: 31px; float: right; padding: 30px 10px 0 0;">
        <div class="clear_both">&nbsp;</div>
    </div>
</div>