<h1>Корзина</h1>
<?php if (!count($this->items)) { ?>
    <p>В корзине пока нету товаров</p>
<?php } else { ?>
    <p>Только что вы заказали у нас такие товары</p>

    <?php foreach ($this->items as $item) { ?>
        <div class="product cart">
            <?php if (!empty($item->thumb)) { ?><a href="<?php echo Rastor_Url::get('product', array('id' => $item->id)) ?>"><img src="<?php echo $item->thumb; ?>" alt=""></a><?php } ?>
            <div class="info">
                <a href="<?php echo Rastor_Url::get('product', array('id' => $item->id)) ?>"><?php echo $item->name; ?></a>
                <div class="count"><?php echo $item->_count; ?> шт.</div>
                <div class="price"><?php echo $item->price; ?> p.</div>
            </div>
            <a href="#" class="remove" onclick="deleteProduct(<?php echo $item->id; ?>, this); return false;">Удалить из корзины</a>
        </div>
    <?php } ?>

    <div class="clear"></div>
    <p>Всего: <?php echo $this->price; ?> р.</p>
    <p>Вы можете их удалить из корзины либо оформить заказ</p>
    <?php echo $this->form; ?>
<?php } ?>